# Movie Recommendor Sysytem

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import ast
import nltk

In [3]:
movies=pd.read_csv("C://Users//ARYA SHARMA//Downloads//archive//tmdb_5000_movies.csv")
credits=pd.read_csv("C://Users//ARYA SHARMA//Downloads//archive//tmdb_5000_credits.csv")

In [4]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
movies.shape

(4803, 20)

In [6]:
credits.shape

(4803, 4)

In [7]:
movies=movies.merge(credits,on='title')

In [8]:
movies.shape

(4809, 23)

In [9]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [10]:
movies=movies.drop(['budget','homepage','original_language','original_title','popularity','production_countries','release_date','tagline','vote_count','production_companies','id','revenue','runtime','spoken_languages','status','vote_average'],axis=1)

In [11]:
movies.head()

,genres,keywords,overview,title,movie_id,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bondâ€™s past sends him o...,Spectre,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,The Dark Knight Rises,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",John Carter,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [12]:
movies.isnull().sum()

genres      0
keywords    0
overview    3
title       0
movie_id    0
cast        0
crew        0
dtype: int64

In [13]:
movies.dropna(inplace=True)

In [14]:
movies.isnull().sum()

genres      0
keywords    0
overview    0
title       0
movie_id    0
cast        0
crew        0
dtype: int64

In [15]:
movies.duplicated().sum()

0

In [16]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [17]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [18]:
movies['genres']=movies['genres'].apply(convert)

In [19]:
movies.head()

,genres,keywords,overview,title,movie_id,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bondâ€™s past sends him o...,Spectre,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,The Dark Knight Rises,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",John Carter,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
movies['keywords']=movies['keywords'].apply(convert)

In [21]:
def convert3(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break
            
    return L

In [22]:
movies['cast']=movies['cast'].apply(convert3)

In [23]:
movies.head()

,genres,keywords,overview,title,movie_id,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,19995,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,285,"[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bondâ€™s past sends him o...,Spectre,206647,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,The Dark Knight Rises,49026,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",John Carter,49529,"[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [24]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [25]:
movies['crew']=movies['crew'].apply(fetch_director)

In [26]:
movies.head()

,genres,keywords,overview,title,movie_id,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,19995,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,285,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bondâ€™s past sends him o...,Spectre,206647,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,The Dark Knight Rises,49026,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",John Carter,49529,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [27]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [28]:
movies['genre']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x] )
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x] )
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x] )
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x] )

In [29]:
movies.head()

,genres,keywords,overview,title,movie_id,cast,crew,genre
0,"[Action, Adventure, Fantasy, Science Fiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,19995,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[Action, Adventure, Fantasy, ScienceFiction]"
1,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,285,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Adventure, Fantasy, Action]"
2,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,206647,"[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[Action, Adventure, Crime]"
3,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...",The Dark Knight Rises,49026,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Action, Crime, Drama, Thriller]"
4,"[Action, Adventure, Science Fiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...",John Carter,49529,"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[Action, Adventure, ScienceFiction]"

In [30]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [31]:
movies.head()

,genres,keywords,overview,title,movie_id,cast,crew,genre,tags
0,"[Action, Adventure, Fantasy, Science Fiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,19995,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,285,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d..."
2,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,206647,"[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[Action, Adventure, Crime]","[A, cryptic, message, from, Bondâ€™s, past, send..."
3,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...",The Dark Knight Rises,49026,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney..."
4,"[Action, Adventure, Science Fiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...",John Carter,49529,"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili..."

In [32]:
new_df=movies[['movie_id','title','tags']]

In [33]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [34]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\ARYA SHARMA\AppData\Local\Temp\ipykernel_19872\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [35]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [36]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy Science Fiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [37]:
new_df['tags']=new_df['tags'].apply(lambda x : x.lower())

C:\Users\ARYA SHARMA\AppData\Local\Temp\ipykernel_19872\3923394162.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x : x.lower())

In [38]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [39]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [40]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [41]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\ARYA SHARMA\AppData\Local\Temp\ipykernel_19872\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [42]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=7000,stop_words='english')

In [43]:
vectors= cv.fit_transform(new_df['tags']).toarray()

In [44]:
cv.get_feature_names()

c:\Users\ARYA SHARMA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '10th',
 '11',
 '12',
 '12th',
 '13',
 '14',
 '15',
 '150',
 '16',
 '16th',
 '17',
 '17th',
 '18',
 '1890',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1930s',
 '1937',
 '1940',
 '1941',
 '1944',
 '1945',
 '1950',
 '1950s',
 '1955',
 '1959',
 '1960',
 '1960s',
 '1962',
 '1964',
 '1965',
 '1967',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1976',
 '1977',
 '1979',
 '1980',
 '1980s',
 '1984',
 '1985',
 '1990',
 '1994',
 '1995',
 '1997',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2000',
 '2001',
 '2002',
 '2003',
 '2008',
 '2009',
 '20th',
 '21st',
 '21stcenturi',
 '23',
 '24',
 '25',
 '27',
 '30',
 '300',
 '35',
 '3d',
 '40',
 '47',
 '50',
 '500',
 '51',
 '60',
 '60s',
 '70',
 '7th',
 '80',
 'aaron',
 'aaroneckhart',
 'aarontaylor',
 'abandon',
 'abbi',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'aborigin',
 'abov',
 'abroad',
 'absolut',
 'absurd',
 'abus',
 'abuse',
 'academ',
 'academi',
 'academy',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'acquir',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'ada',
 'adam',
 'adammckay',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'addiction',
 'addit',
 'addl',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adrift',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'adults',
 'advanc',
 'advantag',
 'advantage',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advice',
 'advis',
 'affair',
 'affect',
 'affection',
 'afflict',
 'affluent',
 'afford',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'afternoon',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'aggressionbyanim',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airborn',
 'aircraft',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alanarkin',
 'alaska',
 'alaskan',
 'albert',
 'albertbrook',
 'albertfinney',
 'alcatraz',
 'alcohol',
 'alcoholabus',
 'alecbaldwin',
 'alejandrogonzÃ¡leziÃ±Ã¡rritu',
 'alex',
 'alexanderpayn',
 'alexanderskarsgÃ¥rd',
 'alexapenavega',
 'alexia',
 'alexisbledel',
 'alexkendrick',
 'alexpettyf',
 'alexproya',
 'alfi',
 'alfredhitchcock',
 'alfredmolina',
 'algeria',
 'ali',
 'alic',
 'alice',
 'alicebraga',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'alike',
 'alilart',
 'aliv',
 'alive',
 'alleg',
 'allegedli',
 'allen',
 'alli',
 'allianc',
 'allies',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alt',
 'alter',
 'altern',
 'alternatehistori',
 'alternater',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandabyn',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'amberheard',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americandream',
 'americanfootbal',
 'americanfootballplay',
 'ami',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientgreec',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'andrewadamson',
 'andrewgarfield',
 'andrewniccol',
 'android',
 'andrzejbartkowiak',
 'andy',
 'andyfickman',
 'andygarcÃ­a',
 'andyserki',
 'andytenn',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animal',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annabel',
 'annafari',
 'annafriel',
 'annakendrick',
 'annasophiarobb',
 'anne',
 'annefletch',
 'annehathaway',
 'annehech',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'answers',
 'ant',
 'antarct',
 'antarctica',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antisemit',
 'antiterror',
 'antoinefuqua',
 'anton',
 'antonio',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'apollo',
 'appar',
 'appear',
 'appl',
 'apple',
 'appli',
 'appoint',
 'appreci',
 'apprehend',
 'apprentic',
 'approach',
 'approaches',
 'april',
 'aquarium',
 'arab',
 'arbitrarylaw',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'archeri',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arizona',
 'arm',
 'armi',
 'armiehamm',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'array',
 'arrest',
 'arrested',
 'arriv',
 'arrive',
 'arrives',
 'arrog',
 'arson',
 'art',
 'artgalleri',
 'arthur',
 'articl',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'artists',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assassins',
 'assault',
 'assembl',
 'assign',
 'assignment',
 'assist',
 'assistant',
 'associ',
 'assort',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atlant',
 'atlanta',
 'atom',
 'atomegoyan',
 'atomicbomb',
 'attach',
 'attack',
 'attacks',
 'attempt',
 'attemptedmurd',
 'attempttoescap',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'audreytaut',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'austria',
 'austrian',
 'author',
 'authorities',
 'authority',
 'autism',
 'auto',
 'autobiograph',
 'automobilerac',
 'avail',
 'aveng',
 'averag',
 'aviat',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awe',
 'awesom',
 'awkward',
 'awri',
 'awry',
 'ax',
 'axe',
 'axel',
 'babe',
 'babi',
 'baby',
 'babysitt',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'backstag',
 'backwat',
 'backyard',
 'bad',
 'badli',
 'bag',
 'bahama',
 'bail',
 'bailey',
 'baker',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbara',
 'barbarian',
 'barbershop',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrier',
 'barry',
 'barrylevinson',
 'barrypepp',
 'barrysonnenfeld',
 'bars',
 'bas',
 'base',
 'basebal',
 'basedonchildren',
 'basedoncomicbook',
 'basedonfilm',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketball',
 'bat',
 'bathtub',
 'batman',
 'battalion',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beaten',
 'beau',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'beg',
 'began',
 'begin',
 'begins',
 'beguil',
 'behavior',
 'behead',
 'belgium',
 'belief',
 'beliefs',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'berniemac',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'betrayal',
 'bettemidl',
 'better',
 'betti',
 'bettythoma',
 'beverli',
 'bibl',
 'biblic',
 'bicker',
 'bicycl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'bilbo',
 'billcondon',
 'billhad',
 'billi',
 'billion',
 'billionair',
 'billmoseley',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billyconnolli',
 'billycrudup',
 'billycryst',
 'bind',
 'biograph',
 'biographi',
 'biolog',
 'biologist',
 'biopic',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitten',
 'bitter',
 'bittersweet',
 'bizarr',
 'black',
 'blackandwhit',
 'blackhol',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blake',
 'blame',
 'blart',
 'blast',
 'blaxploit',
 'blaze',
 'blend',
 'bless',
 'blind',
 'blinddat',
 'blindnessandimpairedvis',
 'bliss',
 'blizzard',
 'block',
 'blofeld',
 'blog',
 'blond',
 'blonde',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'bloom',
 'blossom',
 'blow',
 'blu',
 'blue',
 'blunt',
 'blur',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobby',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bodyhorror',
 'bohemian',
 'bold',
 'bollywood',
 'bolt',
 'bomb',
 'bomber',
 'bond',
 'bone',
 'bonniehunt',
 'boo',
 'book',
 'books',
 'boot',
 'border',
 'bore',
 'boredom',
 'boring',
 'born',
 'borrow',
 'boss',
 'boston',
 'botch',
 'bottl',
 'bounc',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bourn',
 'bout',
 'bowl',
 'box',
 'boxer',
 'boxingmatch',
 'boy',
 'boyd',
 'boyfriend',
 'boys',
 'brad',
 'bradanderson',
 'bradleycoop',
 'bradpitt',
 'brain',
 'braintumor',
 'brainwash',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breakingthefourthwal',
 'breakup',
 'breast',
 'breath',
 'breed',
 'brendan',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brentspin',
 'brettratn',
 'brew',
 'brian',
 'briancox',
 'briandepalma',
 'brianhelgeland',
 'brianlev',
 'brianrobbin',
 'brick',
 'bride',
 'bridesmaid',
 'bridg',
 'bridge',
 'bridgetfonda',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britisharmi',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronson',
 'bronx',
 'brood',
 'brook',
 'brooklyn',
 'brooklynnewyorkc',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brotherhood',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucecampbel',
 'brucedern',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryancranston',
 'bryansing',
 'brycedallashoward',
 'bu',
 'buck',
 'bud',
 'budapest',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'buffalo',
 'bug',
 'build',
 'building',
 'built',
 'bull',
 'bullet',
 'bulli',
 'bum',
 'bumbl',
 'bump',
 'bunch',
 'bunker',
 'bunni',
 'bureaucraci',
 'burglar',
 'buri',
 'burn',
 'burnedal',
 'burtlancast',
 'burton',
 'burtreynold',
 'bush',
 'busi',
 'business',
 'businessman',
 'businesswoman',
 'bust',
 'butch',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'cabl',
 'caesar',
 'cage',
 'cain',
 'cairo',
 'cal',
 'cale',
 'caleb',
 'california',
 'calm',
 'calvin',
 'cambodia',
 'camcord',
 'came',
 'camelot',
 'camera',
 'cameraman',
 'cameron',
 'cameroncrow',
 'camerondiaz',
 'camgigandet',
 'camillabel',
 'camp',
 'campaign',
 'campbel',
 'campbell',
 'campbellscott',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'candlelightvigil',
 'canin',
 'cannabi',
 'cannib',
 'canuxploit',
 'canyon',
 'capabl',
 'cape',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'captured',
 'car',
 'caraccid',
 'carbomb',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'cargo',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carlo',
 'carmen',
 'carniv',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'carriefish',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'casey',
 'caseyaffleck',
 'cash',
 ...]

In [45]:
from sklearn.metrics.pairwise import cosine_similarity

In [46]:
similarity=cosine_similarity(vectors)

In [47]:
cosine_similarity(vectors).shape

(4806, 4806)

In [48]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [49]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf

In [50]:
import pickle

In [51]:
pickle.dump(new_df.to_dict(),open('movies_dict.pkl','wb'))

In [52]:
new_df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bondâ€™ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4805,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4807,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4808,25975,My Date with Drew,ever sinc the second grade when he first saw h...

In [53]:
pickle.dump(similarity,open('similarity.pkl','wb'))